import type { ExpoConfig } from 'expo/config';

/**
 * Native configuration for Renglon.
 *
 * Single source of truth: there is no app.json. The android/ and ios/ directories are
 * gitignored and regenerated by `expo prebuild` (CNG), so any native setting has to be
 * declared here or it gets lost.
 */
const config: ExpoConfig = {
  name: 'Renglón',
  slug: 'renglon',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/images/icon.png',
  scheme: 'renglon',
  userInterfaceStyle: 'automatic',

  android: {
    // Immutable once published on the Play Store.
    package: 'com.eduardopaulcs.renglon',
    versionCode: 1,
    adaptiveIcon: {
      // Icon images are generated by `npm run icons` (scripts/export-icons.mjs).
      backgroundColor: '#1F3A5F',
      foregroundImage: './assets/images/android-icon-foreground.png',
      backgroundImage: './assets/images/android-icon-background.png',
      monochromeImage: './assets/images/android-icon-monochrome.png',
    },
    predictiveBackGestureEnabled: false,
  },

  ios: {
    icon: './assets/expo.icon',
    bundleIdentifier: 'com.eduardopaulcs.renglon',
    supportsTablet: true,
  },

  web: {
    output: 'static',
    favicon: './assets/images/favicon.png',
  },

  plugins: [
    'expo-router',
    'expo-localization',
    [
      'expo-splash-screen',
      {
        // The app's paper background, so the splash hands over to the first screen seamlessly.
        backgroundColor: '#F7F1E3',
        image: './assets/images/splash-icon.png',
        imageWidth: 120,
        dark: {
          backgroundColor: '#1B1A17',
        },
      },
    ],
    [
      // enableFTS compiles FTS3/4/5 into the bundled SQLite. It is a config plugin, which is
      // why the app needs a development build: Expo Go does not apply it.
      'expo-sqlite',
      {
        enableFTS: true,
        useSQLCipher: false,
      },
    ],
    [
      // Explicit minSdk instead of inheriting the SDK default, which changes between Expo
      // releases without notice.
      'expo-build-properties',
      {
        android: {
          minSdkVersion: 24,
          compileSdkVersion: 36,
          targetSdkVersion: 36,
        },
      },
    ],
  ],

  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
};

export default config;
